version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis_mcu_core
    expose:
      - 6379

  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcu_core_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mcu_core_app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    depends_on:
      - db
      - redis
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
      "

volumes:
  db_data:
