version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis_mcu_core
    expose:
      - 6379

  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports: ["5433:5433"]

  app:
    ports:
      - 3001:3001
    build: .  
    volumes:
      - .:/home/app
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails db:create && bundle exec rake db:migrate &&
      bundle exec rails s -p 3001 -b '0.0.0.0'"
